#ifndef __FIRNESS_INCLUDES__
#define __FIRNESS_INCLUDES__

#include <Protocol/HiiDatabase.h>
#include <Library/ShellCommandLib.h>
#include <Protocol/Timer.h>
#include <Protocol/DriverConfiguration.h>
#include <Protocol/Udp4.h>
#include <Library/UefiRuntimeServicesTableLib.h>
#include <Protocol/MpService.h>
#include <CpuPageTable.c>
#include <Protocol/PlatformLogo.h>
#include <Library/PciLib.h>
#include <Library/BaseLib.h>
#include <Protocol/HttpUtilities.h>
#include <Protocol/DiskIo2.h>
#include <Library/BaseMemoryLib.h>
#include <Protocol/Dhcp4.h>
#include <UefiShellDebug1CommandsLib/Mm.c>
#include <Protocol/SimpleTextInEx.h>
#include <Protocol/Ip6.h>
#include <Protocol/HiiPopup.h>
#include <Protocol/Tcp6.h>
#include <Protocol/VlanConfig.h>
#include <Protocol/HiiFont.h>
#include <Protocol/AtaPassThru.h>
#include <Protocol/GuidedSectionExtraction.h>
#include <Protocol/ScsiPassThruExt.h>
#include <Protocol/Decompress.h>
#include <IndustryStandard/Usb.h>
#include <Protocol/UgaDraw.h>
#include <Protocol/GraphicsOutput.h>
#include <Protocol/ScsiPassThru.h>
#include <Protocol/HiiString.h>
#include <Library/DebugLib.h>
#include <Library/UefiBootServicesTableLib.h>
#include <Protocol/AcpiTable.h>
#include <Protocol/DeferredImageLoad.h>
#include <Protocol/FirmwareVolume2.h>
#include <Library/PciExpressLib.h>
#include <Protocol/SimpleFileSystem.h>
#include <Protocol/HiiConfigAccess.h>
#include <Protocol/DriverHealth.h>
#include <Library/MtrrLib.h>
#include <Protocol/FaultTolerantWrite.h>
#include <Protocol/UserManager.h>
#include <Library/IoLib.h>
#include <Protocol/DriverDiagnostics.h>
#include <Protocol/PxeBaseCode.h>
#include <IntelSiliconPkg/Include/Protocol/Spi2.h>
#include <Protocol/UsbIo.h>
#include <Protocol/IpSec.h>
#include <Library/ReportStatusCodeLib.h>
#include <Library/MemoryAllocationLib.h>
#include <Protocol/Dhcp6.h>
#include <Protocol/SmmMemoryAttribute.h>
#include <Protocol/PciIo.h>
#include <Protocol/Dns6.h>
#include <Uefi/UefiMultiPhase.h>
#include <Protocol/FormBrowser2.h>
#include <Library/PrintLib.h>
#include <Protocol/IncompatiblePciDeviceSupport.h>
#include <Shell/ShellParametersProtocol.h>
#include <Protocol/MmSxDispatch.h>
#include <Protocol/SimpleTextOut.h>
#include <Protocol/TcgService.h>
#include <Protocol/DriverDiagnostics2.h>
#include <Protocol/RegularExpressionProtocol.h>
#include <Library/UefiBootManagerLib.h>
#include <Library/UefiApplicationEntryPoint.h>
#include <Protocol/DisplayProtocol.h>
#include <Protocol/SmmBase2.h>
#include <Protocol/PciPlatform.h>
#include <Protocol/SwapAddressRange.h>
#include <Protocol/HiiConfigRouting.h>
#include <Protocol/Tcp4.h>
#include <Library/PcdLib.h>
#include <Protocol/Mtftp6.h>
#include <Protocol/Smbios.h>
#include <Protocol/SerialIo.h>
#include <Protocol/Ip4.h>
#include <Ip6ConfigNv.h>
#include <Library/TimerLib.h>
#include <Protocol/PciRootBridgeIo.h>
#include <ArpImpl.h>
#include <Console/TerminalDxe/Terminal.h>
#include <SimicsOpenBoardPkg/Library/DxeLogoLib/OemBadging.h>
#include <Library/S3BootScriptLib.h>
#include <Protocol/ScsiIo.h>
#include <Protocol/PciHostBridgeResourceAllocation.h>
#include <Protocol/AdapterInformation.h>
#include <Library/SerialPortLib.h>
#include <Uefi/UefiSpec.h>
#include <UefiShellDebug1CommandsLib/Edit/TextEditorTypes.h>
#include <Protocol/DiskIo.h>
#include <Protocol/SimpleNetwork.h>
#include <Protocol/IpSecConfig.h>
#include <Protocol/Udp6.h>
#include <Library/UefiLib.h>
#include <Protocol/Dns4.h>
#include <Protocol/PciHotPlugInit.h>
#include <Protocol/IdeControllerInit.h>
#include <Protocol/FirmwareManagement.h>
#include <Library/UefiRuntimeLib.h>
#include <Library/SynchronizationLib.h>
#include <Protocol/Mtftp4.h>
#include <Protocol/Http.h>
#include <Protocol/CcMeasurement.h>
#include <Protocol/Ip6Config.h>
#include <Protocol/ManagedNetwork.h>

#endif // __FIRNESS_INCLUDES__
